version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    target_branch: "master"
    update_schedule: "weekly"
    default_reviewers:
      - "kamontat"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"
